//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimpleResult", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfIdentvcrQC78O))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfboolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultListOfIdentInfoOctDOWgh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfIdentInfoOctDOWgh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfTechnicianIdentvcrQC78O))]
    public partial class SimpleResult : object
    {
        
        private int CodeField;
        
        private string ErrorField;
        
        private int IdField;
        
        private ServiceReference1.ValidationInfo[] ValidationInfosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ValidationInfo[] ValidationInfos
        {
            get
            {
                return this.ValidationInfosField;
            }
            set
            {
                this.ValidationInfosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfIdentvcrQC78O))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfboolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultListOfIdentInfoOctDOWgh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfIdentInfoOctDOWgh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfTechnicianIdentvcrQC78O))]
    public partial class Result : ServiceReference1.SimpleResult
    {
        
        private System.TimeSpan DurationField;
        
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfIdentvcrQC78O", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    public partial class ResultOfIdentvcrQC78O : ServiceReference1.Result
    {
        
        private ServiceReference1.Ident DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Ident Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    public partial class ResultOfboolean : ServiceReference1.Result
    {
        
        private bool DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultListOfIdentInfoOctDOWgh", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    public partial class ResultListOfIdentInfoOctDOWgh : ServiceReference1.Result
    {
        
        private ServiceReference1.IdentInfo[] DataListField;
        
        private System.Nullable<int> MaxCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IdentInfo[] DataList
        {
            get
            {
                return this.DataListField;
            }
            set
            {
                this.DataListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxCount
        {
            get
            {
                return this.MaxCountField;
            }
            set
            {
                this.MaxCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfIdentInfoOctDOWgh", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    public partial class ResultOfIdentInfoOctDOWgh : ServiceReference1.Result
    {
        
        private ServiceReference1.IdentInfo DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.IdentInfo Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultOfTechnicianIdentvcrQC78O", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    public partial class ResultOfTechnicianIdentvcrQC78O : ServiceReference1.Result
    {
        
        private ServiceReference1.TechnicianIdent DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TechnicianIdent Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationInfo", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    public partial class ValidationInfo : object
    {
        
        private int ErrorcodeField;
        
        private string MessageField;
        
        private ServiceReference1.ParameterObject[] ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Errorcode
        {
            get
            {
                return this.ErrorcodeField;
            }
            set
            {
                this.ErrorcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ParameterObject[] Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechnicianIdent", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    public partial class TechnicianIdent : ServiceReference1.Ident
    {
        
        private int TechnicianIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TechnicianId
        {
            get
            {
                return this.TechnicianIdField;
            }
            set
            {
                this.TechnicianIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterObject", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfTechnicianIdentvcrQC78O))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.SimpleResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ValidationInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ValidationInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ParameterObject[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.TechnicianIdent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.Ident))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfIdentvcrQC78O))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfboolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultListOfIdentInfoOctDOWgh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.ResultOfIdentInfoOctDOWgh))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.IdentInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.IdentInfo))]
    public partial class ParameterObject : object
    {
        
        private string NameField;
        
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ident", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Common.Interface")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.TechnicianIdent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.IdentInfo))]
    public partial class Ident : object
    {
        
        private int[] MandatorIdsField;
        
        private int SystemuserIdField;
        
        private System.DateTime TimestampField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] MandatorIds
        {
            get
            {
                return this.MandatorIdsField;
            }
            set
            {
                this.MandatorIdsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemuserId
        {
            get
            {
                return this.SystemuserIdField;
            }
            set
            {
                this.SystemuserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentInfo", Namespace="http://schemas.datacontract.org/2004/07/BOdega.Authorizer.Interface.Internal.Data" +
        "Types")]
    public partial class IdentInfo : ServiceReference1.Ident
    {
        
        private System.DateTime CreatedField;
        
        private string DisplayNameField;
        
        private string LoginNameField;
        
        private string RequestIPField;
        
        private System.Nullable<int> TechnicianIdField;
        
        private string TechnicianNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created
        {
            get
            {
                return this.CreatedField;
            }
            set
            {
                this.CreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName
        {
            get
            {
                return this.LoginNameField;
            }
            set
            {
                this.LoginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestIP
        {
            get
            {
                return this.RequestIPField;
            }
            set
            {
                this.RequestIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TechnicianId
        {
            get
            {
                return this.TechnicianIdField;
            }
            set
            {
                this.TechnicianIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicianName
        {
            get
            {
                return this.TechnicianNameField;
            }
            set
            {
                this.TechnicianNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAuthorizerInternal")]
    public interface IAuthorizerInternal
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizer/TechnicianLogin", ReplyAction="http://tempuri.org/IAuthorizer/TechnicianLoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfTechnicianIdentvcrQC78O> TechnicianLoginAsync(string loginname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizer/Login", ReplyAction="http://tempuri.org/IAuthorizer/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentvcrQC78O> LoginAsync(string loginname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizer/LoginToDataSource", ReplyAction="http://tempuri.org/IAuthorizer/LoginToDataSourceResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentvcrQC78O> LoginToDataSourceAsync(string loginname, string password, int dataSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizer/Logout", ReplyAction="http://tempuri.org/IAuthorizer/LogoutResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Result> LogoutAsync(ServiceReference1.Ident ident);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizer/IsLoggedIn", ReplyAction="http://tempuri.org/IAuthorizer/IsLoggedInResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfboolean> IsLoggedInAsync(ServiceReference1.Ident ident);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizer/IsLoggedInForMandator", ReplyAction="http://tempuri.org/IAuthorizer/IsLoggedInForMandatorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfboolean> IsLoggedInForMandatorAsync(ServiceReference1.Ident ident, int mandatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizer/AuthenticateHwkUser", ReplyAction="http://tempuri.org/IAuthorizer/AuthenticateHwkUserResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfboolean> AuthenticateHwkUserAsync(string loginname, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizerInternal/HashLogin", ReplyAction="http://tempuri.org/IAuthorizerInternal/HashLoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentvcrQC78O> HashLoginAsync(string pwtoken, string loginname, string passwordhash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizerInternal/GetIdentInfos", ReplyAction="http://tempuri.org/IAuthorizerInternal/GetIdentInfosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultListOfIdentInfoOctDOWgh> GetIdentInfosAsync(string pwtoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorizerInternal/GetIdentInfo", ReplyAction="http://tempuri.org/IAuthorizerInternal/GetIdentInfoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentInfoOctDOWgh> GetIdentInfoAsync(string pwtoken, int systemuserId, int mandator);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IAuthorizerInternalChannel : ServiceReference1.IAuthorizerInternal, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AuthorizerInternalClient : System.ServiceModel.ClientBase<ServiceReference1.IAuthorizerInternal>, ServiceReference1.IAuthorizerInternal
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthorizerInternalClient() : 
                base(AuthorizerInternalClient.GetDefaultBinding(), AuthorizerInternalClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAuthorizerInternal.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizerInternalClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthorizerInternalClient.GetBindingForEndpoint(endpointConfiguration), AuthorizerInternalClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizerInternalClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthorizerInternalClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizerInternalClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthorizerInternalClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthorizerInternalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfTechnicianIdentvcrQC78O> TechnicianLoginAsync(string loginname, string password)
        {
            return base.Channel.TechnicianLoginAsync(loginname, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentvcrQC78O> LoginAsync(string loginname, string password)
        {
            return base.Channel.LoginAsync(loginname, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentvcrQC78O> LoginToDataSourceAsync(string loginname, string password, int dataSource)
        {
            return base.Channel.LoginToDataSourceAsync(loginname, password, dataSource);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Result> LogoutAsync(ServiceReference1.Ident ident)
        {
            return base.Channel.LogoutAsync(ident);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfboolean> IsLoggedInAsync(ServiceReference1.Ident ident)
        {
            return base.Channel.IsLoggedInAsync(ident);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfboolean> IsLoggedInForMandatorAsync(ServiceReference1.Ident ident, int mandatorId)
        {
            return base.Channel.IsLoggedInForMandatorAsync(ident, mandatorId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfboolean> AuthenticateHwkUserAsync(string loginname, string password)
        {
            return base.Channel.AuthenticateHwkUserAsync(loginname, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentvcrQC78O> HashLoginAsync(string pwtoken, string loginname, string passwordhash)
        {
            return base.Channel.HashLoginAsync(pwtoken, loginname, passwordhash);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultListOfIdentInfoOctDOWgh> GetIdentInfosAsync(string pwtoken)
        {
            return base.Channel.GetIdentInfosAsync(pwtoken);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResultOfIdentInfoOctDOWgh> GetIdentInfoAsync(string pwtoken, int systemuserId, int mandator)
        {
            return base.Channel.GetIdentInfoAsync(pwtoken, systemuserId, mandator);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthorizerInternal))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuthorizerInternal))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8092/bodegaAuthorizerInternal");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthorizerInternalClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAuthorizerInternal);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthorizerInternalClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAuthorizerInternal);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuthorizerInternal,
        }
    }
}
